# Site settings
title: Dinsmore Design
email: derek@dinsmore-design.com
description: "We help clients develop their brand, strengthen marketing strategies and acquire life-long customers through creative and visually stunning communication."
info: "A design and web development studio in Mesa, AZ"
message: "We Build Brands"
keywords: "mac,apple,iphone,ios,osx,games,apps,development"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.dinsmoredesign.com" # the base hostname & protocol for your site
twitter_username: companytwitter
# Build settings
markdown: kramdown
author:
    name: Derek Dinsmore
    twitter: yourtwitter
    url: http://www.dinsmoredesign.com
    header_bg: /images/profile-header.png
    avatar: /images/avatar.jpg
    email: derek@dinsmore-design.com
facebook:
    image: /images/delightfuldev-facebook-cover.png
